# Holesovice config
# Extends the mainnet preset
PRESET_BASE: 'mainnet'

# Free-form short name of the network that this configuration applies to
# Must match the regex: [a-z0-9\-]
CONFIG_NAME: 'holesovice'

# Transition
# ---------------------------------------------------------------
# Estimated on Sept 15, 2023
TERMINAL_TOTAL_DIFFICULTY: 0
# By default, don't use these params
TERMINAL_BLOCK_HASH: 0x142926a82d13fd70825fc29bc82f8ae9904b62c102d42ea1f474b5426bcf9093
TERMINAL_BLOCK_HASH_ACTIVATION_EPOCH: 0  # Sep 15, 2023, 2pm UTC


# Genesis
# ---------------------------------------------------------------
# `2**14` (= 16,384)
MIN_GENESIS_ACTIVE_VALIDATOR_COUNT: 8
# Sep 15, 2023, 2pm UTC
MIN_GENESIS_TIME: 1669798000
# Mainnet initial fork version, recommend altering for testnets
GENESIS_FORK_VERSION: 0x00166111
# 3600 seconds (1 hour)
GENESIS_DELAY: 3600


# Forking
# ---------------------------------------------------------------
# Some forks are disabled for now:
#  - These may be re-assigned to another fork-version later
#  - Temporarily set to max uint64 value: 2**64 - 1

# Altair
ALTAIR_FORK_VERSION: 0x01166111
ALTAIR_FORK_EPOCH: 0  # Sep 15, 2023, 2pm UTC
# Bellatrix
BELLATRIX_FORK_VERSION: 0x02166111
BELLATRIX_FORK_EPOCH: 0  # Sep 15, 2023, 2pm UTC
# Capella
CAPELLA_FORK_VERSION: 0x03166111
CAPELLA_FORK_EPOCH: 18446744073709551615  # Disabled
# EIP4844
EIP4844_FORK_VERSION: 0x04166111
EIP4844_FORK_EPOCH: 18446744073709551615  # Disabled

# Time parameters
# ---------------------------------------------------------------
# 12 seconds
SECONDS_PER_SLOT: 12
# 14 (estimate from proof-of-work mainnet)
SECONDS_PER_ETH1_BLOCK: 14
# 2**8 (= 256) epochs ~27 hours
MIN_VALIDATOR_WITHDRAWABILITY_DELAY: 256
# 2**8 (= 256) epochs ~27 hours
SHARD_COMMITTEE_PERIOD: 256
# 256 Eth1 blocks ~1 hour
ETH1_FOLLOW_DISTANCE: 256


# Validator cycle
# ---------------------------------------------------------------
# 2**2 (= 4)
INACTIVITY_SCORE_BIAS: 4
# 2**4 (= 16)
INACTIVITY_SCORE_RECOVERY_RATE: 16
# 2**4 * 10**9 (= 16,000,000,000) Gwei
EJECTION_BALANCE: 16000000000
# 2**2 (= 4)
MIN_PER_EPOCH_CHURN_LIMIT: 4
# 2**16 (= 65,536)
CHURN_LIMIT_QUOTIENT: 65536


# Fork choice
# ---------------------------------------------------------------
# 40%
PROPOSER_SCORE_BOOST: 40

# Deposit contract
# ---------------------------------------------------------------
# Holesovice Testnet
DEPOSIT_CHAIN_ID: 11166111
DEPOSIT_NETWORK_ID: 11166111
DEPOSIT_CONTRACT_ADDRESS: 0x000000006465706F73697420636f6E7472616374
